.TH "Содержание директории iep" 3 "Ср 23 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории iep
.SH SYNOPSIS
.br
.PP
.SS "Директории"

.in +1c
.ti -1c
.RI "директория \fBconsts\fP"
.br
.ti -1c
.RI "директория \fBmanagers\fP"
.br
.ti -1c
.RI "директория \fBstructures\fP"
.br
.in -1c
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBsqlpage\&.php\fP"
.br
.in -1c
