.TH "Specialty" 3 "Ср 23 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Specialty \- Класс, который описывает Специальность  

.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $code, string $description, string $file='')"
.br
.ti -1c
.RI "\fBsetSpecialtyID\fP (int $id)"
.br
.ti -1c
.RI "\fBgetSpecialtyID\fP ()"
.br
.ti -1c
.RI "\fBgetCode\fP ()"
.br
.ti -1c
.RI "\fBgetDescription\fP ()"
.br
.ti -1c
.RI "\fBgetFilepath\fP ()"
.br
.ti -1c
.RI "\fBgetFilename\fP ()"
.br
.ti -1c
.RI "\fBsetFile\fP (string $filename)"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.ti -1c
.RI "\fB$code\fP"
.br
.ti -1c
.RI "\fB$description\fP"
.br
.ti -1c
.RI "\fB$file\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс, который описывает Специальность 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Конструктор(ы)"
.PP 
.SS "__construct (string $code, string $description, string $file = \fC''\fP)"

.PP
\fBАргументы:\fP
.RS 4
\fI$code\fP - Код специальности 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Формат кода специальности 'XX\&.XX\&.XX', где X - число от 0 до 9
.RE
.PP
\fBАргументы:\fP
.RS 4
\fI$description\fP - Описание специальности 
.br
\fI$file\fP - Путь до файла специальности 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Файл в формате PDF 
.RE
.PP

.SH "Методы"
.PP 
.SS "getCode ()"

.PP
\fBВозвращает:\fP
.RS 4
Код специальности 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Формат кода специальности 'XX\&.XX\&.XX', где X - число от 0 до 9 
.RE
.PP

.SS "getDescription ()"

.PP
\fBВозвращает:\fP
.RS 4
Описание специальности 
.RE
.PP

.SS "getFilename ()"

.PP
\fBВозвращает:\fP
.RS 4
Имя файла специальности 
.RE
.PP

.SS "getFilepath ()"

.PP
\fBВозвращает:\fP
.RS 4
Путь до файла специальности 
.RE
.PP

.SS "getSpecialtyID ()"

.PP
\fBВозвращает:\fP
.RS 4
Идентификатор специальности 
.RE
.PP

.SS "setFile (string $filename)"

.PP
\fBВозвращает:\fP
.RS 4
Задаёт путь до файла специальности 
.RE
.PP

.SS "setSpecialtyID (int $id)"

.PP
\fBАргументы:\fP
.RS 4
\fI$id\fP - Идентификатор специальности 
.RE
.PP

.SH "Поля"
.PP 
.SS "$code\fC [private]\fP"

.SS "$description\fC [private]\fP"

.SS "$file\fC [private]\fP"

.SS "$id\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
