.TH "IEP" 3 "Пт 25 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IEP \- Базовый класс для все остальных менеджеров  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'iep/managers/iep\&.class\&.php'\fP
.PP
Производные классы:\fBGroupManager\fP, \fBNewsManager\fP, \fBScheduleManager\fP, \fBSpecialtyManager\fP, \fBSubjectManager\fP, \fBTestManager\fP, \fBTrafficManager\fP и \fBUserManager\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\\PDO $\fBdbc\fP)"
.br
.RI "Задаёт контроллер базы данных "
.ti -1c
.RI "\fBsetDBC\fP ($\fBdbc\fP)"
.br
.RI "Задаёт контроллер базы данных "
.ti -1c
.RI "\fBdbc\fP ()"
.br
.RI "Возвращает контроллер базы данных "
.ti -1c
.RI "\fBquery\fP (string $sql, array $params=array())"
.br
.RI "Выполняет запрос "
.ti -1c
.RI "\fBgetLogs\fP ()"
.br
.RI "Возвращает все записи логов "
.ti -1c
.RI "\fBremoveLogs\fP (int $log_id)"
.br
.RI "Удаляет запись лога "
.ti -1c
.RI "\fBadd\fP ($data)"
.br
.RI "Добавление каких-либо данных в базу данных "
.ti -1c
.RI "\fBremove\fP ($what)"
.br
.RI "Удаление каких-либо данными из базы данных "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$DBC\fP"
.br
.RI "Контроллер базы данных (PDO) "
.in -1c
.SH "Подробное описание"
.PP 
Базовый класс для все остальных менеджеров 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0
.RE
.PP
Все запросы к базе данных осуществляются через PDO
.PP
Базовые функций, выполняемые менеджером:
.IP "1." 4
Добавление данных
.IP "2." 4
Удаление данных
.IP "3." 4
Выполнение запроса к БД напрямую
.IP "4." 4
Работа с логами (Выборка, удаление)
.PP
.PP
Логи ведутся в базе данных:
.IP "1." 4
На добавление
.IP "2." 4
На удаление
.IP "3." 4
На изменение
.PP
.PP
С помощью специальных методов можно получить доступ к логам 
.SH "Конструктор(ы)"
.PP 
.SS "__construct (\\PDO $dbc)"

.PP
Задаёт контроллер базы данных Базовый конструктор для всех унаследованных менеджеров
.PP
\fBАргументы:\fP
.RS 4
\fI$dbc\fP - Контроллер базы данных 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Объект класса PDO 
.RE
.PP

.SH "Методы"
.PP 
.SS "add ( $data)\fC [abstract]\fP"

.PP
Добавление каких-либо данных в базу данных 
.PP
\fBАргументы:\fP
.RS 4
\fI$data\fP - Данные для добавления 
.RE
.PP

.SS "dbc ()"

.PP
Возвращает контроллер базы данных 
.PP
\fBВозвращает:\fP
.RS 4
Контроллер базы данных 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Объект класса PDO 
.RE
.PP

.SS "getLogs ()"

.PP
Возвращает все записи логов 
.PP
\fBВозвращает:\fP
.RS 4
Логи 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с записями 
.RE
.PP

.SS "query (string $sql, array $params = \fCarray()\fP)"

.PP
Выполняет запрос 
.PP
\fBАргументы:\fP
.RS 4
\fI$sql\fP - SQL код 
.br
\fI$params\fP - Аргументы 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE или FALSE, если запрос не предполагает выборку данных, а иначе ассоциативный массив с данными 
.RE
.PP

.SS "remove ( $what)\fC [abstract]\fP"

.PP
Удаление каких-либо данными из базы данных 
.PP
\fBАргументы:\fP
.RS 4
\fI$what\fP - Данные для удаления 
.RE
.PP

.SS "removeLogs (int $log_id)"

.PP
Удаляет запись лога 
.PP
\fBАргументы:\fP
.RS 4
\fI$log_id\fP - идентификатор записи логи 
.RE
.PP

.SS "setDBC ( $dbc)"

.PP
Задаёт контроллер базы данных 
.PP
\fBАргументы:\fP
.RS 4
\fI$dbc\fP - Контроллер базы данных 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Объект класса PDO 
.RE
.PP

.SH "Поля"
.PP 
.SS "$DBC\fC [private]\fP"

.PP
Контроллер базы данных (PDO) 

.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
