.TH "StudentAnswer" 3 "Чт 24 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StudentAnswer \- Класс описывает сущность - ответы студента на тест  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'iep/structures/studentanswer\&.class\&.php'\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($student, string $subject, string $caption, array $answers, string $date, int $mark)"
.br
.ti -1c
.RI "\fBgetStudent\fP ()"
.br
.ti -1c
.RI "\fBgetSubject\fP ()"
.br
.ti -1c
.RI "\fBgetCaption\fP ()"
.br
.ti -1c
.RI "\fBgetAnswers\fP ()"
.br
.ti -1c
.RI "\fBgetPassDate\fP ()"
.br
.ti -1c
.RI "\fBgetMark\fP ()"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$student\fP"
.br
.ti -1c
.RI "\fB$answers\fP"
.br
.ti -1c
.RI "\fB$subject\fP"
.br
.ti -1c
.RI "\fB$caption\fP"
.br
.ti -1c
.RI "\fB$date\fP"
.br
.ti -1c
.RI "\fB$mark\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс описывает сущность - ответы студента на тест 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Конструктор(ы)"
.PP 
.SS "__construct ( $student, string $subject, string $caption, array $answers, string $date, int $mark)"

.SH "Методы"
.PP 
.SS "getAnswers ()"

.SS "getCaption ()"

.SS "getMark ()"

.SS "getPassDate ()"

.SS "getStudent ()"

.SS "getSubject ()"

.SH "Поля"
.PP 
.SS "$answers\fC [private]\fP"

.SS "$caption\fC [private]\fP"

.SS "$date\fC [private]\fP"

.SS "$mark\fC [private]\fP"

.SS "$student\fC [private]\fP"

.SS "$subject\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
