.TH "Student" 3 "Ср 23 Авг 2017" "Version 1.0.0" "EDUKIT Developers Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Student \- Класс описывающий сущность Студент  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBUser\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBUser\fP $user, string $home_address, string $cell_phone, $group)"
.br
.ti -1c
.RI "\fBgetHomeAddress\fP ()"
.br
.ti -1c
.RI "\fBgetCellPhone\fP ()"
.br
.ti -1c
.RI "\fBgetGroup\fP ()"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$home_address\fP"
.br
.ti -1c
.RI "\fB$cell_phone\fP"
.br
.ti -1c
.RI "\fB$group\fP"
.br
.in -1c
.SS "Дополнительные унаследованные члены"
.SH "Подробное описание"
.PP 
Класс описывающий сущность Студент 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Конструктор(ы)"
.PP 
.SS "__construct (\fBUser\fP $user, string $home_address, string $cell_phone,  $group)"

.PP
\fBАргументы:\fP
.RS 4
\fI$user\fP - Объект класса \fBUser\fP 
.br
\fI$home_address\fP - Домашний адрес 
.br
\fI$cell_phone\fP - Сотовый телефон 
.br
\fI$group\fP - Группа 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Объект класса \fBGroup\fP 
.RE
.PP

.SH "Методы"
.PP 
.SS "getCellPhone ()"

.PP
\fBВозвращает:\fP
.RS 4
Сотовый телефон 
.RE
.PP

.SS "getGroup ()"

.PP
\fBВозвращает:\fP
.RS 4
Группу 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Объект класса \fBGroup\fP 
.RE
.PP

.SS "getHomeAddress ()"

.PP
\fBВозвращает:\fP
.RS 4
Домашний адрес 
.RE
.PP

.SH "Поля"
.PP 
.SS "$cell_phone\fC [private]\fP"

.SS "$group\fC [private]\fP"

.SS "$home_address\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers Doc из исходного текста\&.
