.TH "TestQuestion" 3 "Ср 23 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestQuestion
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $question, string $r_answer, array $answers=array())"
.br
.ti -1c
.RI "\fBsetQuestionID\fP (int $id)"
.br
.ti -1c
.RI "\fBgetQuestionID\fP ()"
.br
.ti -1c
.RI "\fBgetQuestion\fP ()"
.br
.ti -1c
.RI "\fBsetAnswers\fP (array $answers)"
.br
.ti -1c
.RI "\fBgetAnswers\fP ()"
.br
.ti -1c
.RI "\fBgetRAnswer\fP ()"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.ti -1c
.RI "\fB$question\fP"
.br
.ti -1c
.RI "\fB$answers\fP"
.br
.ti -1c
.RI "\fB$r_answer\fP"
.br
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "__construct (string $question, string $r_answer, array $answers = \fCarray()\fP)"

.SH "Методы"
.PP 
.SS "getAnswers ()"

.SS "getQuestion ()"

.SS "getQuestionID ()"

.SS "getRAnswer ()"

.SS "setAnswers (array $answers)"

.SS "setQuestionID (int $id)"

.SH "Поля"
.PP 
.SS "$answers\fC [private]\fP"

.SS "$id\fC [private]\fP"

.SS "$question\fC [private]\fP"

.SS "$r_answer\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
