.TH "IEP\Structures" 3 "Чт 24 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IEP\Structures
.SH SYNOPSIS
.br
.PP
.SS "Структуры данных"

.in +1c
.ti -1c
.RI "class \fBGroup\fP"
.br
.RI "Класс, который несёт в себе информацию об группе "
.ti -1c
.RI "class \fBNews\fP"
.br
.RI "Класс, который хранит в себе информацию об новости "
.ti -1c
.RI "class \fBParent_\fP"
.br
.RI "Класс для хранения данных об родителе "
.ti -1c
.RI "class \fBSpecialty\fP"
.br
.RI "Класс, который описывает Специальность "
.ti -1c
.RI "class \fBStudent\fP"
.br
.RI "Класс описывающий сущность Студент "
.ti -1c
.RI "class \fBStudentAnswer\fP"
.br
.RI "Класс описывает сущность - ответы студента на тест "
.ti -1c
.RI "class \fBStudentTest\fP"
.br
.RI "Класс описывающий сущность результатов теста "
.ti -1c
.RI "class \fBSubject\fP"
.br
.RI "Класс, который несёт в себе информацию об предмете "
.ti -1c
.RI "class \fBTeacher\fP"
.br
.RI "Класс описывает сущность пользователя Преподаватель "
.ti -1c
.RI "class \fBTest\fP"
.br
.RI "Класс описывает сущность - тест "
.ti -1c
.RI "class \fBTestQuestion\fP"
.br
.RI "Класс описывает вопрос к тесту "
.ti -1c
.RI "class \fBTrafficEntry\fP"
.br
.RI "Запись об посещамости "
.ti -1c
.RI "class \fBUser\fP"
.br
.RI "Общий класс для всех пользователей "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
