.TH "StudentAnswer" 3 "Вс 17 Сен 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StudentAnswer \- Класс описывает сущность - ответы студента на тест, которые отправятся на запись в бд  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'iep/structures/studentanswer\&.class\&.php'\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($student, string $subject, string $caption, array $answers, string $date, int $mark)"
.br
.ti -1c
.RI "\fBgetStudent\fP ()"
.br
.RI "Возвращает студента "
.ti -1c
.RI "\fBgetSubject\fP ()"
.br
.RI "Возвращает предмет теста "
.ti -1c
.RI "\fBgetCaption\fP ()"
.br
.RI "Возвращает заголовок теста "
.ti -1c
.RI "\fBgetAnswers\fP ()"
.br
.RI "Возвращает ответы студента "
.ti -1c
.RI "\fBgetPassDate\fP ()"
.br
.RI "Возвращает дату сдачи теста "
.ti -1c
.RI "\fBgetMark\fP ()"
.br
.RI "Возвращает оценку за тест "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$student\fP"
.br
.RI "Студент "
.ti -1c
.RI "\fB$answers\fP"
.br
.RI "Ответы "
.ti -1c
.RI "\fB$subject\fP"
.br
.RI "Предмет "
.ti -1c
.RI "\fB$caption\fP"
.br
.RI "Заголовок теста "
.ti -1c
.RI "\fB$date\fP"
.br
.RI "Дата сдачи "
.ti -1c
.RI "\fB$mark\fP"
.br
.RI "Оценка "
.in -1c
.SH "Подробное описание"
.PP 
Класс описывает сущность - ответы студента на тест, которые отправятся на запись в бд 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Конструктор(ы)"
.PP 
.SS "__construct ( $student, string $subject, string $caption, array $answers, string $date, int $mark)"

.PP
\fBАргументы:\fP
.RS 4
\fI$student\fP - Студент, который проходил тест 
.br
\fI$subject\fP - Предмет 
.br
\fI$caption\fP - Заголовок теста 
.br
\fI$answers\fP - Ответы 
.br
\fI$date\fP - Дата сдачи 
.br
\fI$mark\fP - Оценка 
.RE
.PP

.SH "Методы"
.PP 
.SS "getAnswers ()"

.PP
Возвращает ответы студента 
.PP
\fBВозвращает:\fP
.RS 4
Ответы 
.RE
.PP

.SS "getCaption ()"

.PP
Возвращает заголовок теста 
.PP
\fBВозвращает:\fP
.RS 4
Заголовок теста 
.RE
.PP

.SS "getMark ()"

.PP
Возвращает оценку за тест 
.PP
\fBВозвращает:\fP
.RS 4
Оценка за тест 
.RE
.PP

.SS "getPassDate ()"

.PP
Возвращает дату сдачи теста 
.PP
\fBВозвращает:\fP
.RS 4
Дата сдачи теста 
.RE
.PP

.SS "getStudent ()"

.PP
Возвращает студента 
.PP
\fBВозвращает:\fP
.RS 4
Студент 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Объект класса \fBStudent\fP 
.RE
.PP

.SS "getSubject ()"

.PP
Возвращает предмет теста 
.PP
\fBВозвращает:\fP
.RS 4
Предмет 
.RE
.PP

.SH "Поля"
.PP 
.SS "$answers\fC [private]\fP"

.PP
Ответы 
.SS "$caption\fC [private]\fP"

.PP
Заголовок теста 
.SS "$date\fC [private]\fP"

.PP
Дата сдачи 
.SS "$mark\fC [private]\fP"

.PP
Оценка 
.SS "$student\fC [private]\fP"

.PP
Студент 
.SS "$subject\fC [private]\fP"

.PP
Предмет 

.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
