.TH "Teacher" 3 "Пт 25 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Teacher \- Класс описывает сущность пользователя Преподаватель  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'iep/structures/teacher\&.class\&.php'\fP
.PP
Базовые классы:\fBUser\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBUser\fP $user, string $info)"
.br
.ti -1c
.RI "\fBsetNews\fP (array $news)"
.br
.ti -1c
.RI "\fBsetSubjects\fP (array $subjects)"
.br
.ti -1c
.RI "\fBsetTests\fP (array $tests)"
.br
.ti -1c
.RI "\fBgetInfo\fP ()"
.br
.ti -1c
.RI "\fBgetNews\fP ()"
.br
.ti -1c
.RI "\fBgetSubjects\fP ()"
.br
.ti -1c
.RI "\fBgetStrSubjects\fP ()"
.br
.ti -1c
.RI "\fBgetTests\fP ()"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$info\fP"
.br
.ti -1c
.RI "\fB$news\fP"
.br
.ti -1c
.RI "\fB$subjects\fP"
.br
.ti -1c
.RI "\fB$tests\fP"
.br
.in -1c
.SS "Дополнительные унаследованные члены"
.SH "Подробное описание"
.PP 
Класс описывает сущность пользователя Преподаватель 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Конструктор(ы)"
.PP 
.SS "__construct (\fBUser\fP $user, string $info)"

.PP
\fBАргументы:\fP
.RS 4
\fI$user\fP - Объект класса \fBUser\fP 
.br
\fI$info\fP - Информация об преподавтеле 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Может быть описана в формате HTML 
.RE
.PP

.SH "Методы"
.PP 
.SS "getInfo ()"

.PP
\fBВозвращает:\fP
.RS 4
Информацию об преподавтеле 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Информация может быть описана в HTML 
.RE
.PP

.SS "getNews ()"

.PP
\fBВозвращает:\fP
.RS 4
Опубликованные новости 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBNews\fP 
.RE
.PP

.SS "getStrSubjects ()"

.PP
\fBВозвращает:\fP
.RS 4
Список предметов разделённых запятой 
.RE
.PP
\fBПредупреждения:\fP
.RS 4
Тестовый метод 
.RE
.PP

.SS "getSubjects ()"

.PP
\fBВозвращает:\fP
.RS 4
Предметы, которые ведёт преподавтель 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBSubject\fP 
.RE
.PP

.SS "getTests ()"

.PP
\fBВозвращает:\fP
.RS 4
Созданные тесты 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBTest\fP 
.RE
.PP

.SS "setNews (array $news)"

.PP
\fBАргументы:\fP
.RS 4
\fI$news\fP - Опубликованные новости 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBNews\fP 
.RE
.PP

.SS "setSubjects (array $subjects)"

.PP
\fBАргументы:\fP
.RS 4
\fI$subjects\fP - Предметы, которые ведёт преподавтель 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBSubject\fP 
.RE
.PP

.SS "setTests (array $tests)"

.PP
\fBАргументы:\fP
.RS 4
\fI$tests\fP - Тесты, которые создал преподавтель 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBTest\fP 
.RE
.PP

.SH "Поля"
.PP 
.SS "$info\fC [private]\fP"

.SS "$news\fC [private]\fP"

.SS "$subjects\fC [private]\fP"

.SS "$tests\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
