.TH "Test" 3 "Чт 24 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test \- Класс описывает сущность - тест  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'iep/structures/test\&.class\&.php'\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $caption, $subject, $author, array $for_groups=array())"
.br
.ti -1c
.RI "\fBsetTestID\fP (int $id)"
.br
.ti -1c
.RI "\fBgetTestID\fP ()"
.br
.ti -1c
.RI "\fBsetSubject\fP ($subject)"
.br
.ti -1c
.RI "\fBgetSubject\fP ()"
.br
.ti -1c
.RI "\fBgetCaption\fP ()"
.br
.ti -1c
.RI "\fBsetAuthor\fP ($author)"
.br
.ti -1c
.RI "\fBgetAuthor\fP ()"
.br
.ti -1c
.RI "\fBsetGroups\fP (array $groups)"
.br
.ti -1c
.RI "\fBgetGroups\fP ()"
.br
.ti -1c
.RI "\fBsetQuestions\fP (array $questions)"
.br
.ti -1c
.RI "\fBgetQuestions\fP ()"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.ti -1c
.RI "\fB$caption\fP"
.br
.ti -1c
.RI "\fB$subject\fP"
.br
.ti -1c
.RI "\fB$author\fP"
.br
.ti -1c
.RI "\fB$questions\fP"
.br
.ti -1c
.RI "\fB$for_groups\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс описывает сущность - тест 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Конструктор(ы)"
.PP 
.SS "__construct (string $caption,  $subject,  $author, array $for_groups = \fCarray()\fP)"

.SH "Методы"
.PP 
.SS "getAuthor ()"

.SS "getCaption ()"

.SS "getGroups ()"

.SS "getQuestions ()"

.SS "getSubject ()"

.SS "getTestID ()"

.SS "setAuthor ( $author)"

.SS "setGroups (array $groups)"

.SS "setQuestions (array $questions)"

.SS "setSubject ( $subject)"

.SS "setTestID (int $id)"

.SH "Поля"
.PP 
.SS "$author\fC [private]\fP"

.SS "$caption\fC [private]\fP"

.SS "$for_groups\fC [private]\fP"

.SS "$id\fC [private]\fP"

.SS "$questions\fC [private]\fP"

.SS "$subject\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
