.TH "Test" 3 "Вс 17 Сен 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test \- Класс описывает сущность - тест  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'iep/structures/test\&.class\&.php'\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $caption, $subject, $author, array $for_groups=array())"
.br
.ti -1c
.RI "\fBsetTestID\fP (int $id)"
.br
.RI "Задаёт идентификатор теста "
.ti -1c
.RI "\fBgetTestID\fP ()"
.br
.RI "Возвращает идентификатор теста "
.ti -1c
.RI "\fBsetSubject\fP ($subject)"
.br
.RI "Задаёт предмет "
.ti -1c
.RI "\fBgetSubject\fP ()"
.br
.RI "Возвращает предмет "
.ti -1c
.RI "\fBgetCaption\fP ()"
.br
.RI "Возвращает заголовок теста "
.ti -1c
.RI "\fBgetAuthor\fP ()"
.br
.RI "Возвращает почту преподавателя "
.ti -1c
.RI "\fBsetGroups\fP (array $groups)"
.br
.RI "Задаёт группы, которые могут проходить тест "
.ti -1c
.RI "\fBgetGroups\fP ()"
.br
.RI "Возвращает группы, которые могут проходить тест "
.ti -1c
.RI "\fBsetQuestions\fP (array $questions)"
.br
.RI "Задаёт вопросы "
.ti -1c
.RI "\fBgetQuestions\fP ()"
.br
.RI "Возвращает вопросы теста "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.RI "Идентификатор теста "
.ti -1c
.RI "\fB$caption\fP"
.br
.RI "Заголовок теста "
.ti -1c
.RI "\fB$subject\fP"
.br
.RI "Предмет, привязанный к тесту "
.ti -1c
.RI "\fB$author\fP"
.br
.RI "Электронная почта преподавателя "
.ti -1c
.RI "\fB$questions\fP"
.br
.RI "Вопросы "
.ti -1c
.RI "\fB$for_groups\fP"
.br
.RI "Группы, которые могут проходить тест "
.in -1c
.SH "Подробное описание"
.PP 
Класс описывает сущность - тест 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Конструктор(ы)"
.PP 
.SS "__construct (string $caption,  $subject,  $author, array $for_groups = \fCarray()\fP)"

.PP
\fBАргументы:\fP
.RS 4
\fI$caption\fP - Заголовок теста 
.br
\fI$subject\fP - Предмет 
.br
\fI$author\fP - Электронная почта преподавателя 
.br
\fI$for_groups\fP - Группы, которые могут проходить тест 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBGroup\fP 
.RE
.PP

.SH "Методы"
.PP 
.SS "getAuthor ()"

.PP
Возвращает почту преподавателя 
.PP
\fBВозвращает:\fP
.RS 4
Электронная почта преподавателя 
.RE
.PP

.SS "getCaption ()"

.PP
Возвращает заголовок теста 
.PP
\fBВозвращает:\fP
.RS 4
Заголовок теста 
.RE
.PP

.SS "getGroups ()"

.PP
Возвращает группы, которые могут проходить тест 
.PP
\fBВозвращает:\fP
.RS 4
Группы 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBSubject\fP 
.RE
.PP

.SS "getQuestions ()"

.PP
Возвращает вопросы теста 
.PP
\fBВозвращает:\fP
.RS 4
Вопросы 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBTestQuestion\fP 
.RE
.PP

.SS "getSubject ()"

.PP
Возвращает предмет 
.PP
\fBВозвращает:\fP
.RS 4
Предмет 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Объект класса \fBSubject\fP 
.RE
.PP

.SS "getTestID ()"

.PP
Возвращает идентификатор теста 
.PP
\fBВозвращает:\fP
.RS 4
Идентификатор теста 
.RE
.PP

.SS "setGroups (array $groups)"

.PP
Задаёт группы, которые могут проходить тест 
.PP
\fBАргументы:\fP
.RS 4
\fI$groups\fP - Группы 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBSubject\fP 
.RE
.PP

.SS "setQuestions (array $questions)"

.PP
Задаёт вопросы 
.PP
\fBАргументы:\fP
.RS 4
\fI$questions\fP - Вопросы 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBTestQuestion\fP 
.RE
.PP

.SS "setSubject ( $subject)"

.PP
Задаёт предмет 
.PP
\fBВозвращает:\fP
.RS 4
Предмет 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Объект класса \fBSubject\fP 
.RE
.PP

.SS "setTestID (int $id)"

.PP
Задаёт идентификатор теста 
.PP
\fBАргументы:\fP
.RS 4
\fI$id\fP - Идентификатор теста 
.RE
.PP

.SH "Поля"
.PP 
.SS "$author\fC [private]\fP"

.PP
Электронная почта преподавателя 
.SS "$caption\fC [private]\fP"

.PP
Заголовок теста 
.SS "$for_groups\fC [private]\fP"

.PP
Группы, которые могут проходить тест 
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBGroup\fP 
.RE
.PP

.SS "$id\fC [private]\fP"

.PP
Идентификатор теста 
.SS "$questions\fC [private]\fP"

.PP
Вопросы 
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса \fBTestQuestion\fP 
.RE
.PP

.SS "$subject\fC [private]\fP"

.PP
Предмет, привязанный к тесту 
.PP
\fBЗаметки:\fP
.RS 4
Объект класса \fBSubject\fP 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
