.TH "TrafficManager" 3 "Ср 23 Авг 2017" "Version 1.0.0" "EDUKIT Developers Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrafficManager \- Менеджер для работы с записями посещамости  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIEP\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBadd\fP ($traffic_entry)"
.br
.RI "Добавляет новую запись об посещамости студента "
.ti -1c
.RI "\fBremove\fP ($traffic_entry)"
.br
.RI "Удаляет запись об посещамости студента "
.in -1c
.SH "Подробное описание"
.PP 
Менеджер для работы с записями посещамости 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0
.RE
.PP
Задачи менеджера:
.IP "1." 4
Добавлять новые записи об посещамости студента
.IP "2." 4
Получать список записей об посещамости конкретного студента
.IP "3." 4
Получать весь список записей посещамости студентов 
.PP

.SH "Методы"
.PP 
.SS "add ( $traffic_entry)"

.PP
Добавляет новую запись об посещамости студента 
.PP
\fBАргументы:\fP
.RS 4
\fI$traffic_entry\fP - Запись об посещамости 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Объект класса TrafficEntry 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE - успешно, FALSE - ошибка 
.RE
.PP

.SS "remove ( $traffic_entry)"

.PP
Удаляет запись об посещамости студента 
.PP
\fBАргументы:\fP
.RS 4
\fI$traffic_entry\fP - 
.RE
.PP
\fBПредупреждения:\fP
.RS 4
Ожидает реализации 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers Doc из исходного текста\&.
