.TH "NewsManager" 3 "Ср 23 Авг 2017" "Version 1.0.0" "EDUKIT Developers Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewsManager \- Менеджер для работы с новостями  

.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIEP\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBadd\fP ($news)"
.br
.RI "Добавление новой новости "
.ti -1c
.RI "\fBaddAdminNews\fP ($news)"
.br
.RI "Добавление новой новости администратором "
.ti -1c
.RI "\fBgetNews\fP (string $teacher_email)"
.br
.RI "Возвращает все новости опубликованные преподавателем "
.ti -1c
.RI "\fBgetAdminNews\fP (string $admin_email)"
.br
.RI "Возвращает все новости опубликованные администратором "
.ti -1c
.RI "\fBgetAllNews\fP ()"
.br
.RI "Возвращает все опубликованные новости "
.ti -1c
.RI "\fBchangeCaptionNews\fP (int $news_id, string $new_caption)"
.br
.RI "Изменяет заголовок новости "
.ti -1c
.RI "\fBchangeContentNews\fP (int $news_id, string $new_conent)"
.br
.RI "Изменяет содержимое новости "
.ti -1c
.RI "\fBremove\fP ($news_id)"
.br
.RI "Возвращает все опубликованные новости "
.in -1c
.SH "Подробное описание"
.PP 
Менеджер для работы с новостями 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Методы"
.PP 
.SS "add ( $news)"

.PP
Добавление новой новости 
.PP
\fBЗаметки:\fP
.RS 4
Метод используется для добавления новостей преподавателем 
.RE
.PP
\fBАргументы:\fP
.RS 4
\fI$news\fP - новости 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE - успешно, FALSE - ошибка 
.RE
.PP

.SS "addAdminNews ( $news)"

.PP
Добавление новой новости администратором 
.PP
\fBЗаметки:\fP
.RS 4
Метод используется для добавления новостей администратором 
.RE
.PP
\fBАргументы:\fP
.RS 4
\fI$news\fP - Новости 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса News 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE - успешно, FALSE - ошибка 
.RE
.PP

.SS "changeCaptionNews (int $news_id, string $new_caption)"

.PP
Изменяет заголовок новости 
.PP
\fBАргументы:\fP
.RS 4
\fI$news_id\fP - Идентификатор новости 
.br
\fI$new_caption\fP - Новое содержимое 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Содержимое новости может быть представлено в формате HTML 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE - успешно, FALSE - ошибка 
.RE
.PP

.SS "changeContentNews (int $news_id, string $new_conent)"

.PP
Изменяет содержимое новости 
.PP
\fBАргументы:\fP
.RS 4
\fI$news_id\fP - Идентификатор новости 
.br
\fI$new_conent\fP - Новое содержимое 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Содержимое новости может быть представлено в формате HTML 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE - успешно, FALSE - ошибка 
.RE
.PP

.SS "getAdminNews (string $admin_email)"

.PP
Возвращает все новости опубликованные администратором 
.PP
\fBАргументы:\fP
.RS 4
\fI$admin_email\fP - электронная почта администратора 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Новости 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса News 
.RE
.PP

.SS "getAllNews ()"

.PP
Возвращает все опубликованные новости 
.PP
\fBВозвращает:\fP
.RS 4
Новости 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса News 
.RE
.PP

.SS "getNews (string $teacher_email)"

.PP
Возвращает все новости опубликованные преподавателем 
.PP
\fBАргументы:\fP
.RS 4
\fI$teacher_email\fP - электронная почта преподавателя 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Новости 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса News 
.RE
.PP

.SS "remove ( $news_id)"

.PP
Возвращает все опубликованные новости 
.PP
\fBАргументы:\fP
.RS 4
\fI$news_id\fP - Идентификатор новости 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE - успешно, FALSE - ошибка 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers Doc из исходного текста\&.
