.TH "Subject" 3 "Вс 17 Сен 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Subject \- Класс, который несёт в себе информацию об предмете  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'iep/structures/subject\&.class\&.php'\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $description)"
.br
.ti -1c
.RI "\fBsetSubjectID\fP (int $id)"
.br
.RI "Задаёт идентификатор предмета "
.ti -1c
.RI "\fBgetSubjectID\fP ()"
.br
.RI "Возвращает идентификатор предмета "
.ti -1c
.RI "\fBgetDescription\fP ()"
.br
.RI "Возвращает название предмета "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.RI "Идентификатор "
.ti -1c
.RI "\fB$description\fP"
.br
.RI "Название предмета "
.in -1c
.SH "Подробное описание"
.PP 
Класс, который несёт в себе информацию об предмете 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0
.RE
.PP
Класс представляет собой сущность, в которую помещаются данные из базы данных 
.SH "Конструктор(ы)"
.PP 
.SS "__construct (string $description)"

.PP
\fBАргументы:\fP
.RS 4
\fI$description\fP - Название предмета 
.RE
.PP

.SH "Методы"
.PP 
.SS "getDescription ()"

.PP
Возвращает название предмета 
.PP
\fBВозвращает:\fP
.RS 4
Название предмета 
.RE
.PP

.SS "getSubjectID ()"

.PP
Возвращает идентификатор предмета 
.PP
\fBВозвращает:\fP
.RS 4
Идентификатор предмета 
.RE
.PP

.SS "setSubjectID (int $id)"

.PP
Задаёт идентификатор предмета 
.PP
\fBАргументы:\fP
.RS 4
\fI$id\fP - Идентификатор предмета 
.RE
.PP

.SH "Поля"
.PP 
.SS "$description\fC [private]\fP"

.PP
Название предмета 
.SS "$id\fC [private]\fP"

.PP
Идентификатор 

.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
