.TH "StudentTest" 3 "Ср 23 Авг 2017" "Version 1.0.0" "EDUKIT Developers Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StudentTest \- Класс описывающий сущность результатов теста  

.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $student, string $caption, string $subject, string $date_pass, int $mark)"
.br
.ti -1c
.RI "\fBsetTestID\fP (int $id)"
.br
.ti -1c
.RI "\fBgetTestID\fP ()"
.br
.ti -1c
.RI "\fBsetTestAuthor\fP (string $test_author)"
.br
.ti -1c
.RI "\fBgetTestAuthor\fP ()"
.br
.ti -1c
.RI "\fBgetStudent\fP ()"
.br
.ti -1c
.RI "\fBgetCaption\fP ()"
.br
.ti -1c
.RI "\fBgetSubject\fP ()"
.br
.ti -1c
.RI "\fBgetDatePass\fP ()"
.br
.ti -1c
.RI "\fBgetMark\fP ()"
.br
.ti -1c
.RI "\fBsetAnswers\fP (array $answers)"
.br
.ti -1c
.RI "\fBgetAnswers\fP ()"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$id_test\fP"
.br
.ti -1c
.RI "\fB$test_author\fP"
.br
.ti -1c
.RI "\fB$student\fP"
.br
.ti -1c
.RI "\fB$caption\fP"
.br
.ti -1c
.RI "\fB$subject\fP"
.br
.ti -1c
.RI "\fB$date_pass\fP"
.br
.ti -1c
.RI "\fB$mark\fP"
.br
.ti -1c
.RI "\fB$answers\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс описывающий сущность результатов теста 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Конструктор(ы)"
.PP 
.SS "__construct (string $student, string $caption, string $subject, string $date_pass, int $mark)"

.PP
\fBАргументы:\fP
.RS 4
\fI$student\fP - Email студента 
.br
\fI$caption\fP - Название теста 
.br
\fI$subject\fP - Предмет 
.br
\fI$date_pass\fP - Дата сдачи 
.br
\fI$mark\fP - Оценка 
.RE
.PP

.SH "Методы"
.PP 
.SS "getAnswers ()"

.PP
\fBВозвращает:\fP
.RS 4
Массив с ответами 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Формат массива [[question, answer], [question, answer], \&.\&.\&.] 
.RE
.PP

.SS "getCaption ()"

.PP
\fBВозвращает:\fP
.RS 4
Название теста 
.RE
.PP

.SS "getDatePass ()"

.PP
\fBВозвращает:\fP
.RS 4
Дату сдачи теста 
.RE
.PP

.SS "getMark ()"

.PP
\fBВозвращает:\fP
.RS 4
Оценку за тест 
.RE
.PP

.SS "getStudent ()"

.PP
\fBВозвращает:\fP
.RS 4
Email студента 
.RE
.PP

.SS "getSubject ()"

.PP
\fBВозвращает:\fP
.RS 4
Предмет 
.RE
.PP

.SS "getTestAuthor ()"

.PP
\fBВозвращает:\fP
.RS 4
Автора теста 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Формат 'Фамилия И\&.О\&.' 
.RE
.PP

.SS "getTestID ()"

.PP
\fBВозвращает:\fP
.RS 4
Идентификатор пройденного теста 
.RE
.PP

.SS "setAnswers (array $answers)"

.PP
\fBАргументы:\fP
.RS 4
\fI$answers\fP - массив с ответами 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Формат массива [[question, answer], [question, answer], \&.\&.\&.] 
.RE
.PP

.SS "setTestAuthor (string $test_author)"

.PP
\fBАргументы:\fP
.RS 4
\fI$test_author\fP - Автор теста 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Формат 'Фамилия И\&.О\&.' 
.RE
.PP

.SS "setTestID (int $id)"

.PP
\fBАргументы:\fP
.RS 4
\fI$id\fP - Идентификатор пройденного теста 
.RE
.PP

.SH "Поля"
.PP 
.SS "$answers\fC [private]\fP"

.SS "$caption\fC [private]\fP"

.SS "$date_pass\fC [private]\fP"

.SS "$id_test\fC [private]\fP"

.SS "$mark\fC [private]\fP"

.SS "$student\fC [private]\fP"

.SS "$subject\fC [private]\fP"

.SS "$test_author\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers Doc из исходного текста\&.
