.TH "TrafficEntry" 3 "Ср 23 Авг 2017" "Version 1.0.0" "EDUKIT Developers Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrafficEntry
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $student_email, string $date_visit, int $count_passed_pair, int $count_all_pair)"
.br
.ti -1c
.RI "\fBsetTrafficID\fP (int $id)"
.br
.ti -1c
.RI "\fBgetTrafficID\fP ()"
.br
.ti -1c
.RI "\fBgetStudentEmail\fP ()"
.br
.ti -1c
.RI "\fBgetDateVisit\fP ()"
.br
.ti -1c
.RI "\fBgetCountPassedPair\fP ()"
.br
.ti -1c
.RI "\fBgetCountAllPair\fP ()"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.ti -1c
.RI "\fB$email\fP"
.br
.ti -1c
.RI "\fB$date_visit\fP"
.br
.ti -1c
.RI "\fB$count_passed_pair\fP"
.br
.ti -1c
.RI "\fB$count_all_pair\fP"
.br
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "__construct (string $student_email, string $date_visit, int $count_passed_pair, int $count_all_pair)"

.SH "Методы"
.PP 
.SS "getCountAllPair ()"

.SS "getCountPassedPair ()"

.SS "getDateVisit ()"

.SS "getStudentEmail ()"

.SS "getTrafficID ()"

.SS "setTrafficID (int $id)"

.SH "Поля"
.PP 
.SS "$count_all_pair\fC [private]\fP"

.SS "$count_passed_pair\fC [private]\fP"

.SS "$date_visit\fC [private]\fP"

.SS "$email\fC [private]\fP"

.SS "$id\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers Doc из исходного текста\&.
