.TH "SpecialtyManager" 3 "Ср 23 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpecialtyManager
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:\fBIEP\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBadd\fP ($spec)"
.br
.ti -1c
.RI "\fBgetAllSpecialty\fP ()"
.br
.ti -1c
.RI "\fBchangeCodeSpecialty\fP (int $spec_id, string $code)"
.br
.ti -1c
.RI "\fBchangeDescpSpecialty\fP (int $spec_id, string $descp)"
.br
.ti -1c
.RI "\fBchangeFileSpecialty\fP (int $spec_id, string $file)"
.br
.ti -1c
.RI "\fBremove\fP ($spec_id)"
.br
.in -1c
.SH "Методы"
.PP 
.SS "add ( $spec)"

.SS "changeCodeSpecialty (int $spec_id, string $code)"

.SS "changeDescpSpecialty (int $spec_id, string $descp)"

.SS "changeFileSpecialty (int $spec_id, string $file)"

.SS "getAllSpecialty ()"

.SS "remove ( $spec_id)"


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
