.TH "Group" 3 "Ср 23 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Group \- Класс, который несёт в себе информацию об группе  

.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP (string $number, $spec, string $year_education, int $is_budget=1)"
.br
.ti -1c
.RI "\fB__call\fP ($method, $args)"
.br
.ti -1c
.RI "\fBsetGroupID\fP (int $id)"
.br
.ti -1c
.RI "\fBgetGroupID\fP ()"
.br
.ti -1c
.RI "\fBgetNumberGroup\fP ()"
.br
.ti -1c
.RI "\fBgetSpec\fP ()"
.br
.ti -1c
.RI "\fBgetYearEducation\fP ()"
.br
.ti -1c
.RI "\fBgetStatus\fP ()"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.ti -1c
.RI "\fB$number\fP"
.br
.ti -1c
.RI "\fB$spec\fP"
.br
.ti -1c
.RI "\fB$year_education\fP"
.br
.ti -1c
.RI "\fB$is_budget\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс, который несёт в себе информацию об группе 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0
.RE
.PP
Класс представляет собой сущность, в которую помещаются данные из базы данных 
.SH "Конструктор(ы)"
.PP 
.SS "__construct (string $number,  $spec, string $year_education, int $is_budget = \fC1\fP)"

.PP
\fBАргументы:\fP
.RS 4
\fI$number\fP - название группы
.br
\fI$spec\fP - специальность 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Представляет собой объект класса \fBSpecialty\fP
.RE
.PP
\fBАргументы:\fP
.RS 4
\fI$year_education\fP - год выпуска 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Указывается в формате [год]/[год]
.RE
.PP
\fBАргументы:\fP
.RS 4
\fI$is_budget\fP - тип группы 
.RE
.PP
\fBЗаметки:\fP
.RS 4
1 - бюджетная, 0 - коммерческая 
.RE
.PP

.SH "Методы"
.PP 
.SS "__call ( $method,  $args)"

.PP
\fBАргументы:\fP
.RS 4
\fI$method\fP - вызываемый метод 
.br
\fI$args\fP - аргументы вызываемого метода 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Вызов существующего метода
.RE
.PP
\fBПредупреждения:\fP
.RS 4
.RE
.PP
\fB\fP
.RS 4
Конкретно в этом классе переопределён метод \fB__call()\fP\&. Это было сделано для того, чтобы убрать 'паравозик' при вызове методов из объекта
.RE
.PP
\fB\fP
.RS 4
Например, чтобы раньше получить код специальности, нужно было писать: $group->\fBgetSpec()\fP->getCode()
.RE
.PP
\fB\fP
.RS 4
После переопределения метода _call() можно писать: $group->getCode()
.RE
.PP
\fB\fP
.RS 4
В обоих случаях мы получаем код специальности 
.RE
.PP

.SS "getGroupID ()"

.PP
\fBВозвращает:\fP
.RS 4
Идентификатор группы 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Далее идентификатор используется для манипуляций с данными в базе данных 
.RE
.PP

.SS "getNumberGroup ()"

.PP
\fBВозвращает:\fP
.RS 4
Название группы 
.RE
.PP

.SS "getSpec ()"

.PP
\fBВозвращает:\fP
.RS 4
Объект типа \fBSpecialty\fP 
.RE
.PP

.SS "getStatus ()"

.PP
\fBВозвращает:\fP
.RS 4
Возвращает статус группы 
.RE
.PP

.SS "getYearEducation ()"

.PP
\fBВозвращает:\fP
.RS 4
Возвращает год обучения 
.RE
.PP

.SS "setGroupID (int $id)"

.PP
\fBАргументы:\fP
.RS 4
\fI$id\fP - идентификатор группы 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Идентификатор берётся из базы данных 
.RE
.PP

.SH "Поля"
.PP 
.SS "$id\fC [private]\fP"

.SS "$is_budget\fC [private]\fP"

.SS "$number\fC [private]\fP"

.SS "$spec\fC [private]\fP"

.SS "$year_education\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
