.TH "SpecialtyManager" 3 "Чт 24 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpecialtyManager \- Менеджер для работы со специальностями  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'iep/managers/sm\&.class\&.php'\fP
.PP
Базовые классы:\fBIEP\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBadd\fP ($spec)"
.br
.RI "Добавляет новую специальность "
.ti -1c
.RI "\fBgetAllSpecialty\fP ()"
.br
.RI "Возвращает все специальности "
.ti -1c
.RI "\fBchangeCodeSpecialty\fP (int $spec_id, string $code)"
.br
.RI "Изменяет код специальности "
.ti -1c
.RI "\fBchangeDescpSpecialty\fP (int $spec_id, string $descp)"
.br
.RI "Изменяет название специальности "
.ti -1c
.RI "\fBchangeFileSpecialty\fP (int $spec_id, string $file)"
.br
.RI "Изменяет файл специальности "
.ti -1c
.RI "\fBremove\fP ($spec_id)"
.br
.RI "Удаляет специальность "
.in -1c
.SH "Подробное описание"
.PP 
Менеджер для работы со специальностями 


.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Методы"
.PP 
.SS "add ( $spec)"

.PP
Добавляет новую специальность 
.PP
\fBАргументы:\fP
.RS 4
\fI$spec\fP - Специальность 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Объект класс Specialty 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE - успешно, FALSE - ошибка 
.RE
.PP

.SS "changeCodeSpecialty (int $spec_id, string $code)"

.PP
Изменяет код специальности 
.PP
\fBАргументы:\fP
.RS 4
\fI$spec_id\fP - Идентификатор специальности 
.br
\fI$code\fP - Новый код специальности 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Формат кода специальности 'ХХ\&.ХХ\&.ХХ', где Х - число от 0 до 9 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE - успешно, FALSE - ошибка 
.RE
.PP

.SS "changeDescpSpecialty (int $spec_id, string $descp)"

.PP
Изменяет название специальности 
.PP
\fBАргументы:\fP
.RS 4
\fI$spec_id\fP - Идентификатор специальности 
.br
\fI$descp\fP - Новое название специальности 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE - успешно, FALSE - ошибка 
.RE
.PP

.SS "changeFileSpecialty (int $spec_id, string $file)"

.PP
Изменяет файл специальности 
.PP
\fBАргументы:\fP
.RS 4
\fI$spec_id\fP - Идентификатор специальности 
.br
\fI$file\fP - Путь до файла специальности 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Файл должен быть в формате PDF 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE - успешно, FALSE - ошибка 
.RE
.PP

.SS "getAllSpecialty ()"

.PP
Возвращает все специальности 
.PP
\fBВозвращает:\fP
.RS 4
Специальности 
.RE
.PP
\fBЗаметки:\fP
.RS 4
Массив с объектами класса Specialty 
.RE
.PP

.SS "remove ( $spec_id)"

.PP
Удаляет специальность 
.PP
\fBАргументы:\fP
.RS 4
\fI$spec_id\fP - Идентификатор специальности 
.RE
.PP
\fBВозвращает:\fP
.RS 4
TRUE - успешно, FALSE - ошибка 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
