.TH "iep/structures/news.class.php" 3 "Чт 24 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iep/structures/news.class.php
.SH SYNOPSIS
.br
.PP
.SS "Структуры данных"

.in +1c
.ti -1c
.RI "class \fBNews\fP"
.br
.RI "Класс, который хранит в себе информацию об новости "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBIEP\\Structures\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
