.TH "sql_info" 3 "Пт 25 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sql_infoБаза данных SQL 
 \- 
.SH "Общие сведения"
.PP
.SH "Технология доступа к базе данных"
.PP
.SH "Основные объекты базы данных"
.PP
Подразделы: \fBТаблицы\fP, \fBПредставления\fP, \fBФункции\fP, \fBХранимые процедуры\fP, \fBТриггеры\fP
.SS "Таблицы"
В этом разделе описываются все таблицы, включая их поля, типы данных и индексы
.PP
.SS "Представления"
.SS "Функции"
Ниже приведён список функций, которые используются для возврата идентификаторов
.PP
.SS "Хранимые процедуры"
.SS "Триггеры"
 
