.TH "sql_info" 3 "Чт 24 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sql_infoБаза данных SQL 
 \- 
.SH "Общие сведения"
.PP
.SH "Технология доступа к базе данных"
.PP
.SH "Основные объекты базы данных"
.PP
Подразделы: \fBТаблицы\fP, \fBПредставления\fP
.SS "Таблицы"
В этом разделе описываются все таблицы, включая их поля, типы данных и индексы
.PP
.SS "Представления"
Здесь описываем представления 
