.TH "iep/structures/teacher.class.php" 3 "Ср 23 Авг 2017" "Version 1.0.0" "EDUKIT Developers Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iep/structures/teacher.class.php
.SH SYNOPSIS
.br
.PP
.SS "Структуры данных"

.in +1c
.ti -1c
.RI "class \fBTeacher\fP"
.br
.RI "Класс описывает сущность пользователя Преподаватель "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBIEP\\Structures\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers Doc из исходного текста\&.
