.TH "iep/structures/trafficentry.class.php" 3 "Пт 25 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iep/structures/trafficentry.class.php
.SH SYNOPSIS
.br
.PP
.SS "Структуры данных"

.in +1c
.ti -1c
.RI "class \fBTrafficEntry\fP"
.br
.RI "Запись об посещамости "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBIEP\\Structures\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
