.TH "iep/consts/typeusers.consts.php" 3 "Чт 24 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iep/consts/typeusers.consts.php
.SH SYNOPSIS
.br
.PP
.SS "Переменные"

.PP
.RI "\fBТипы пользователей\fP"
.br
По этим константам проверяется уровень доступа к функциональным возможностям сайта
.PP
\fBАвтор:\fP
.RS 4
pmswga 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
.in +1c
.in +1c
.ti -1c
.RI "const \fBUSER_TYPE_TEACHER\fP = 1"
.br
.RI "Преподаватель "
.ti -1c
.RI "const \fBUSER_TYPE_ELDER\fP = 2"
.br
.RI "Староста "
.ti -1c
.RI "const \fBUSER_TYPE_STUDENT\fP = 3"
.br
.RI "Студент "
.ti -1c
.RI "const \fBUSER_TYPE_PARENT\fP = 4"
.br
.RI "Родитель "
.in -1c
.in -1c
.SH "Переменные"
.PP 
.SS "const USER_TYPE_ELDER = 2"

.PP
Староста 
.SS "const USER_TYPE_PARENT = 4"

.PP
Родитель 
.SS "const USER_TYPE_STUDENT = 3"

.PP
Студент 
.SS "const USER_TYPE_TEACHER = 1"

.PP
Преподаватель 
.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
