.TH "iep/managers/um.class.php" 3 "Ср 23 Авг 2017" "Version 1.0" "EDUKIT Developers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iep/managers/um.class.php
.SH SYNOPSIS
.br
.PP
.SS "Структуры данных"

.in +1c
.ti -1c
.RI "class \fBUserManager\fP"
.br
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBIEP\\Managers\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для EDUKIT Developers из исходного текста\&.
